image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images
  name: console-frontend
host: ""
tenantDomain: ""

fasit:
  tenant:
    name: # mapped in fasit
gitHub:
  organization: # mapped in fasit
slack:
  token:
  feedbackChannel: "#console-user-feedback"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

replicaCount: 2
